import os
os.system('cd /sdcard')
try:os.mkdir('Hasil')
except OSError:pass
print ('\033[1;97m[1] 2008 \n[2] 2009\n[3] 2010\n[4] 2011\n[5] 2012\n[6] 2013\n[7] 2014')
ny = input('Hasil Tahun : ')
if ny =='':
    print ('Jangan Kosong Anjing')
    os.system('python nyimpen.py')
elif ny == '1' or ny == '01':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2008.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2008.txt\033[1;97m')
elif ny == '2' or ny == '02':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2009.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2009.txt\033[1;97m')
elif ny == '3' or ny == '03':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2010.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2010.txt\033[1;97m')
elif ny == '4' or ny == '04':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2011.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2011.txt\033[1;97m')
elif ny == '5' or ny == '05':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2012.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2012.txt\033[1;97m')
elif ny == '6' or ny == '06':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2013.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2013.txt\033[1;97m')
elif ny == '7' or ny == '07':
    nm = input('[#] Nama  : ')
    em = input('[#] Email : ')
    ik = input('[#] ID    : ')
    pw = input('[#] Sandi : ')
    tt = input('[#] TTL   : ')
    cd = input('[#] Code  : ')
    kg = open('/sdcard/Hasil/Hasil-2014.txt','a')
    kg.write('\nNama  : '+nm+'\nEmail : '+em+'\nID    : '+ik+'\nSandi : '+pw+'\nTTL   : '+tt+'\nCode  : '+cd+'\n')
    kg.close()
    print ('[√] File Tersimpan Di : \033[1;92m/sdcard/Hasil/Hasil-2014.txt\033[1;97m')
else:
    exit()